apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../../../manifests/catalog
configMapGenerator:
- name: catalog-env
  namespace: catalog
  env: config.properties
vars:
- name: CATALOG_RDS_ENDPOINT
  objref:
    kind: ConfigMap
    name: catalog-env
    apiVersion: v1
  fieldref:
    fieldpath: data.CATALOG_RDS_ENDPOINT
- name: CATALOG_RDS_PASSWORD
  objref:
    kind: ConfigMap
    name: catalog-env
    apiVersion: v1
  fieldref:
    fieldpath: data.CATALOG_RDS_PASSWORD
patches:
- catalog-configMap.yaml
- secrets.yaml
resources:
- nlb.yaml
configurations:
- configuration.yaml
