apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: mq-ack-options
  envs:
  - mq-ack-options.env
vars:
- name: ORDERS_PASSWORD
  objref:
    kind: ConfigMap
    name: mq-ack-options
    apiVersion: v1
  fieldref:
    fieldpath: data.ORDERS_PASSWORD
configurations:
  - env-var-transformer.yaml
resources:
- mq-configmap-orders.yaml
- mq-fieldexports-orders.yaml
