varReference:
- apiVersion: ec2.services.k8s.aws/v1alpha1
  kind: SecurityGroup
  path: spec/vpcID
  value: rds-ack-options
- apiVersion: ec2.services.k8s.aws/v1alpha1
  kind: SecurityGroup
  path: metadata/name
  value: rds-ack-options
- apiVersion: ec2.services.k8s.aws/v1alpha1
  kind: SecurityGroup
  path: spec/name
  value: rds-ack-options
- apiVersion: ec2.services.k8s.aws/v1alpha1
  kind: SecurityGroup
  path: spec/ingressRules[]/ipRanges[]/cidrIP
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBSubnetGroup
  path: spec/subnetIDs
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBSubnetGroup
  path: metadata/name
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBSubnetGroup
  path: spec/name
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBInstance
  path: spec/dbSubnetGroupRef/from/name
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBInstance
  path: metadata/name
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBInstance
  path: spec/dbInstanceIdentifier
  value: rds-ack-options
- apiVersion: rds.services.k8s.aws/v1alpha1
  kind: DBInstance
  path: spec/vpcSecurityGroupRefs[]/from/name
  value: rds-ack-options
