apiVersion: v1
kind: Pod
metadata:
  name: catalog-pod
  namespace: catalog
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/component: service
    app.kubernetes.io/created-by: eks-workshop
spec:
  containers:
  - name: catalog
    image: public.ecr.aws/aws-containers/retail-store-sample-catalog:1.2.1
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: catalog
    - secretRef:
        name: catalog-db
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
