apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog
resources:
  - namespace.yaml
  - secrets.yaml
  - configMap.yaml
  - serviceAccount.yaml
  - service.yaml
  - service-mysql.yaml
  - deployment.yaml
  - statefulset-mysql.yaml
