apiVersion: v2
name: retail-store-sample-chart
description: A Helm chart for the AWS retail store cart component
type: application
version: 0.0.1
dependencies:
  - name: retail-store-sample-cart-chart
    alias: carts
    version: 1.2.1
    repository: oci://public.ecr.aws/aws-containers
