apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: carts
resources:
  - namespace.yaml
  - configMap.yaml
  - serviceAccount.yaml
  - service.yaml
  - service-db.yaml
  - deployment.yaml
  - deployment-db.yaml
