apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: checkoutroute
  namespace: checkout
spec:
  parentRefs:
    - name: ${EKS_CLUSTER_NAME}
      sectionName: http
  rules:
    - backendRefs:
        - name: checkout
          namespace: checkout
          kind: Service
          port: 80
          weight: 25
        - name: checkout
          namespace: checkoutv2
          kind: Service
          port: 80
          weight: 75
