apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: inferentia-inf2
spec:
  template:
    metadata:
      labels:
        instanceType: inferentia-inf2
        provisionerType: Karpenter
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["inf2"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["inf2.24xlarge", "inf2.48xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        name: inferentia-inf2
      taints:
        - key: aws.amazon.com/neuron
          value: "true"
          effect: "NoSchedule"
  disruption:
    consolidateAfter: 300s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h

---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: inferentia-inf2
spec:
  amiFamily: AL2
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 500Gi
        volumeType: gp3
  role: ${KARPENTER_NODE_ROLE}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${EKS_CLUSTER_NAME}
  tags:
    app.kubernetes.io/created-by: eks-workshop
