name: Publish Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.22.12'
      id: install
    - name: Install netlify CLI
      run: npm install -g netlify-cli@11.8.3
    - name: Deploy site
      working-directory: website
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        ENABLE_INDEX: 1
      run: |
        BUILD_ID=${GITHUB_SHA::7}

        export MANIFESTS_REF="${BUILD_ID}"

        source .kustomize-env

        npm install
        npm run deploy:netlify -- --prod
    - name: Update latest tag
      uses: actions/github-script@v6
      with:
        script: |       
          github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/latest`,
              sha: context.sha
          })
