name: Publish PR Preview

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
    - website/**
    - environment/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.22.12'
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Deploy Preview
    - name: Deploying comment
      id: comment-deploying
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: |
          ## Deploy Preview
          Preview site deployment in progress...
    - name: Install netlify CLI
      run: npm install -g netlify-cli@11.8.3
    - name: Deploy site
      id: deploy-site
      working-directory: website
      env:
        PR_ID: ${{ github.event.pull_request.number }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        npm install
        npm run deploy:netlify -- --alias pr-${PR_ID}

        echo "::set-output name=preview::pr-${PR_ID}--eksworkshop-v2-next.netlify.app"
    - name: Deployed comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: ${{ steps.comment-deploying.outputs.comment-id }}
        edit-mode: replace
        body: |
          ## Deploy Preview
          Check out the preview at: https://${{ steps.deploy-site.outputs.preview }}