name: Test - Introduction

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 2"

permissions:
  id-token: write
  contents: read

jobs:
  test-module:
    uses: ./.github/workflows/module-test.yaml
    with:
      module: introduction
    secrets: inherit
