name: Test - Fundamentals

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

permissions:
  id-token: write
  contents: read

jobs:
  test-module:
    strategy:
      fail-fast: false
      matrix:
        module:
          - fundamentals/managed-node-groups**
          - fundamentals/fargate**
          - fundamentals/exposing**
          - fundamentals/storage/{efs,ebs,s3}**
          - fundamentals/storage/{fsx}**
    uses: ./.github/workflows/module-test.yaml
    with:
      glob: ${{ matrix.module }}
    secrets: inherit
