name: Test Utility CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    paths:
    - test/util/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node_version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install NPM packages
      working-directory: test/util
      run: npm ci
    - name: Build
      working-directory: test/util
      run: npm run build
    - name: Run unit tests
      working-directory: test/util
      run: |
        npm test
    - name: Run test content
      working-directory: test/util
      run: |
        npm run exec -- test ./test-content
